---
# Competition No 03 : BDAIO Mock 3

---
## 01 Importing Libraries

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

---
## 02 Loading Datasets

In [2]:
train = pd.read_csv('/kaggle/input/competitions/bd-aio-2026-mock/train.csv')
test  = pd.read_csv('/kaggle/input/competitions/bd-aio-2026-mock/test.csv')
samp  = pd.read_csv('/kaggle/input/competitions/bd-aio-2026-mock/sample_submission.csv')

---
## 03 Simple EDA

In [3]:
train

,id,variety,weight_g,size_cm,color_score,firmness_score,days_since_bloom,brix
0,1,Himsagar,271.3,29.1,7.4,2.3,109,21.08
1,2,Langra,251.0,25.1,10.0,4.4,117,19.10
2,3,Langra,217.9,25.7,7.6,5.3,105,16.33
3,4,Gopalbhog,274.4,32.7,4.3,1.3,107,18.58
4,5,Himsagar,340.2,23.8,5.2,3.3,123,22.05
...,...,...,...,...,...,...,...,...
1995,1996,Gopalbhog,263.2,30.6,NaN,5.7,158,19.57
1996,1997,Langra,314.2,31.4,7.9,5.4,83,16.80
1997,1998,Himsagar,128.7,26.6,8.1,3.1,150,23.08
1998,1999,Himsagar,130.7,28.1,4.7,3.8,129,19.49
1999,2000,Himsagar,225.2,25.4,5.4,7.5,84,15.60

In [4]:
test

,id,variety,weight_g,size_cm,color_score,firmness_score,days_since_bloom
0,1,Himsagar,304.9,34.6,7.5,4.9,100
1,2,Himsagar,171.7,27.5,4.9,5.8,115
2,3,Langra,100.0,24.3,6.0,4.8,115
3,4,Himsagar,278.6,25.1,6.8,2.6,108
4,5,Himsagar,262.2,28.5,7.6,6.9,125
...,...,...,...,...,...,...,...
795,796,Gopalbhog,284.2,22.0,4.4,4.3,103
796,797,Himsagar,244.3,22.6,4.1,4.8,109
797,798,Gopalbhog,278.3,26.5,5.1,6.7,79
798,799,Langra,217.1,35.3,6.1,5.7,107
799,800,Himsagar,247.6,24.6,8.4,6.0,95

In [5]:
samp

      id  brix
0      1  14.5
1      2  14.5
2      3  14.5
3      4  14.5
4      5  14.5
..   ...   ...
795  796  14.5
796  797  14.5
797  798  14.5
798  799  14.5
799  800  14.5

[800 rows x 2 columns]

In [6]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                2000 non-null   int64
 1   variety           2000 non-null   object
 2   weight_g          2000 non-null   float64
 3   size_cm           2000 non-null   float64
 4   color_score       1915 non-null   float64
 5   firmness_score    1919 non-null   float64
 6   days_since_bloom  2000 non-null   int64
 7   brix              2000 non-null   float64
dtypes: float64(5), int64(2), object(1)
memory usage: 125.1+ KB

In [7]:
train.describe()

,id,weight_g,size_cm,color_score,firmness_score,days_since_bloom,brix
count,2000.000000,2000.000000,2000.000000,1915.000000,1919.000000,2000.000000,2000.000000
mean,1000.500000,253.537600,28.077150,5.913525,5.037259,100.253000,17.332820
std,577.494589,62.887187,4.068866,1.972369,1.941362,20.407896,2.397104
min,1.000000,100.400000,15.000000,1.000000,1.000000,60.000000,9.410000
25%,500.750000,215.275000,25.300000,4.550000,3.700000,86.000000,15.680000
50%,1000.500000,250.400000,28.100000,5.900000,5.000000,99.000000,17.250000
75%,1500.250000,284.225000,30.825000,7.300000,6.300000,113.000000,18.960000
max,2000.000000,810.600000,41.100000,10.000000,10.000000,188.000000,25.790000

---
## 04 Data Preprocessing

In [8]:
train.isna().sum()

id                   0
variety              0
weight_g             0
size_cm              0
color_score         85
firmness_score      81
days_since_bloom     0
brix                 0
dtype: int64

In [9]:
test.isna().sum()

id                   0
variety              0
weight_g             0
size_cm              0
color_score         27
firmness_score      31
days_since_bloom     0
dtype: int64

In [10]:
train.color_score.median(), train.color_score.mean()

(5.9, np.float64(5.913524804177546))

In [11]:
train.color_score = train.color_score.fillna(5.9)

In [12]:
test.color_score.median(), test.color_score.mean()

(6.0, np.float64(5.999223803363519))

In [13]:
test.color_score = test.color_score.fillna(6.0)

In [14]:
train.firmness_score.median(), train.firmness_score.mean()

(5.0, np.float64(5.0372589890568005))

In [15]:
train.firmness_score = train.firmness_score.fillna(5.0)

In [16]:
test.firmness_score.median(), test.firmness_score.mean()

(5.0, np.float64(4.963589076723017))

In [17]:
test.firmness_score = test.firmness_score.fillna(5.0)

In [18]:
# one encoding :
one_hot_train = pd.get_dummies(train, columns=['variety'])
one_hot_test = pd.get_dummies(test, columns=['variety'])

In [19]:
train.isna().sum()

id                  0
variety             0
weight_g            0
size_cm             0
color_score         0
firmness_score      0
days_since_bloom    0
brix                0
dtype: int64

In [20]:
test.isna().sum()

id                  0
variety             0
weight_g            0
size_cm             0
color_score         0
firmness_score      0
days_since_bloom    0
dtype: int64

In [21]:
# features and target dividing :
X = one_hot_train.drop(columns='brix')
y = one_hot_train.brix

In [22]:
# Standardization ;
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaled_train = scaler.fit_transform(X)
scaled_test  = scaler.fit_transform(one_hot_test)

In [23]:
# dataset splittin :
from sklearn.model_selection import train_test_split

X_scaled , X_val , y_scaled, y_val = train_test_split(scaled_train, y, test_size=0.2, random_state= 19)
X_scaled_n, X_val_n ,  y_scaled_n, y_val_n = train_test_split(X, y, test_size=0.2, random_state= 19)

---
## 05 Model Building

In [24]:
# linear Regression
from sklearn.linear_model import LinearRegression, Ridge

ln = LinearRegression()
rg = Ridge()

ln.fit(X_scaled, y_scaled)
ln_scl_pred = ln.predict(X_val)

In [25]:
rg.fit(X_scaled, y_scaled)
rg_scl_pred = rg.predict(X_val)

In [26]:
ln.fit(X_scaled_n, y_scaled_n)
ln_scln_pred = ln.predict(X_val)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [27]:
rg.fit(X_scaled_n, y_scaled_n)
rg_scln_pred = rg.predict(X_val)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

## 06 Evaluation

In [28]:
from sklearn.metrics import root_mean_squared_error as rmse

print('Linear Regression Accuricy without scale :',  rmse(y_val, ln_scln_pred))
print('Linear Regression Accuricy with    scale :',  rmse(y_val, ln_scl_pred))
print()
print('Ridge Regression Accuricy without scale :',  rmse(y_val, rg_scln_pred))
print('Ridge Regression Accuricy with    scale :',  rmse(y_val, rg_scl_pred))

Linear Regression Accuricy without scale : 10.655830870312778
Linear Regression Accuricy with    scale : 1.1398296287143865

Ridge Regression Accuricy without scale : 10.654361567336133
Ridge Regression Accuricy with    scale : 1.1396799470891692

---
## 07 Final Prediction

In [29]:
ln.fit(scaled_train, y)
final_pred_ln = ln.predict(scaled_test)

rg.fit(scaled_train, y)
final_pred_rg = rg.predict(scaled_test)

---
## 08 Submission

In [30]:
# Linear Regression
ln_submission = pd.DataFrame({
    'id'   : test.id,
    'brix' : final_pred_ln
})

# Ridge Regression
rg_submission = pd.DataFrame({
    'id'   : test.id,
    'brix' : final_pred_rg
})

In [31]:
ln_submission.to_csv('linear_submission.csv', index=False)
rg_submission.to_csv('Ridge_submission.csv', index=False)

Finished